### ISSUE TITLE
[Style, Fix] Weird color difference on "review completed" screen

### ISSUE THREAD

**Issue by ebanDev** [Shirajuki/anki-redesign#13] opened 2022-01-25 16:19 UTC
The two white/grays colors at the background look a bit weird here ;)
![Kuvakaappaus 2022-01-25 17-18-15](https://user-images.githubusercontent.com/57091497/151015972-939901d2-75b3-4df5-8d15-4b03bef6d7e5.png)

**Comment by Shirajuki** [comment] 2022-01-28 15:15
Hmm, I couldn't reproduce the bug as expected. Would you tell

**Comment by Shirajuki** [comment] 2022-01-28 15:16
Hmm, I couldn't reproduce the bug myself. I only get a "Congratulations! You have finished this deck for now." message with no links as well as the correct background color.
What Anki version are you on? Would you mind adding an image of your enabled addons aswell? :D

**Comment by ebanDev** [comment] 2022-02-02 09:22
Yup ! Running the version ⁨2.1.49 (dc80804a)⁩
Here are my addons :
![Kuvakaappaus 2022-02-02 10-22-18](https://user-images.githubusercontent.com/57091497/152126590-aa727a1a-0481-4b3d-a5bb-02994362a527.png)

**Comment by Shirajuki** [comment] 2022-04-13 00:04
Hello once again (x3). Since the new major update after commit c64c34de94cf46a63cd8c808ed73eb882a80257d, I have added the customized colors through QPalettes and edited the generated color mapping. Again, I haven't had the time to use Anki that much so I cannot reproduce this issue sorry, however the update should in theory fix this problem.

I'll be closing this issue for now, feel free to reopen this if the problem still exists. Thank you very much again for being an user of Anki-redesign!

**Closed by Shirajuki** 2022-04-13 00:04 UTC
Labels: bug
