### ISSUE TITLE
[Bug] Review heatmap is (a bit) cropped

### ISSUE THREAD

**Issue by ebanDev** [Shirajuki/anki-redesign#11] opened 2022-01-25 16:00 UTC
![Kuvakaappaus 2022-01-25 17-00-19](https://user-images.githubusercontent.com/57091497/151012463-69e60370-9275-493f-9b81-350440957df8.png)
As you can see here, the top of review heatmap buttons is a bit cropped :/

**Comment by Shirajuki** [comment] 2022-01-28 16:21
Hmm, I have squinted my eyes lots and can't seem to see any cropping. As other issues, would you mind telling me the Anki version you're using? 😌😊 It would make the debugging work a lot more easier 💪

**Comment by ebanDev** [comment] 2022-02-02 09:25
Yup, as said previously I use
Version ⁨2.1.49 (dc80804a)⁩
Python 3.8.1 Qt 5.15.1 PyQt 5.15.1

and the latest Review Heatmap version ;)

**Comment by Shirajuki** [comment] 2022-04-13 00:06
Heyo! Since the new major update after commit c64c34de94cf46a63cd8c808ed73eb882a80257d, I have reworked the code and styles. Again, I don't see the issue on my devices, however I believe the problem should still be fixed in the new update

I'll leave issue still open, feel free to close this if the problem is fixed for you too. 😊

**Comment by Shirajuki** [comment] 2022-07-05 09:28
Closing this issue! :)

**Closed by Shirajuki** 2022-07-05 09:28 UTC
Labels: bug
