### ISSUE TITLE
[Bug] Body not centered

### ISSUE THREAD

**Issue by ebanDev** [Shirajuki/anki-redesign#8] opened 2022-01-25 15:54 UTC
Hey ! It seems that the <body> is not centered :
![Kuvakaappaus 2022-01-25 16-53-43](https://user-images.githubusercontent.com/57091497/151011351-7b27eefd-6438-4325-888c-22bc66b58821.png)

**Comment by ebanDev** [comment] 2022-01-25 15:55
Maybe it's just my card template idk, but I didn't had this issue without the addon soooo... 😅

**Comment by Shirajuki** [comment] 2022-01-30 18:26
Is it possible for you to send me your card template? It'll greatly make it a lot easier to debug. For the Overview webview, I have only added 3 lines of styling. The styling should also for the most part not affect the overall styling of any card template:
```css
body.card {
    width: 90%;
    margin: 20px auto;
    max-width: 1080px;
}
```
I might have to just remove the styling edits in Overview webview if necessary.

**Comment by ebanDev** [comment] 2022-02-02 09:24
Here is an example : https://file.io/8N7xDytCkGkj !

**Comment by Shirajuki** [comment] 2022-04-13 00:09
Hello! I didn't have the time to see through your Card template some months ago due to being busy with studies, the link seem to be expired, would you mind sending it again? I'll try my best to see if I can fix this issue :D

Feel free to close this if the problem is long fixed otherwise :)

**Comment by Shirajuki** [comment] 2022-07-10 14:17
I'll be closing this issue for now!
Feel free to open a new issue if this matter is still not fixed! :D

**Closed by Shirajuki** 2022-07-10 14:17 UTC
Labels: bug
