### ISSUE TITLE
Visual glitch (running 2.1.49)

### ISSUE THREAD

**Issue by Hovvdy** [Shirajuki/anki-redesign#38] opened 2022-07-27 02:26 UTC
![RedesignGlitch](https://user-images.githubusercontent.com/110075948/181146994-956479ed-4509-46d5-9cdd-afa5472ae7f4.png)
 
I have a glitch that I can replicate by either pressing "F" to create a filtered deck or whenever I click "Anki-redesign" in the toolbar. A small square takes up the top left corner of the screen and will not remove itself unless I restart Anki.

**Comment by Shirajuki** [comment] 2022-07-27 06:53
Hello!
This is actually quite strange, version 2.1.49 of Anki is my main version for testing and this same problem has never occurred to me. Would you mind sending me a list of all your enabled add-ons as well as your operating system of use?
This is probably an add-on compatibility bug. You can test if my theory is correct by disabling all other add-ons, just leaving Anki-redesign enabled, and see if the same problem occurs or not.

**Comment by Hovvdy** [comment] 2022-07-27 16:11
<img width="432" alt="image" src="https://user-images.githubusercontent.com/110075948/181296627-c1899ae9-3c4d-4c8a-bd9c-1f251884828c.png">

I am running Windows 10.

**Comment by Hovvdy** [comment] 2022-07-27 16:12
This occurred before I added "Contaki" and "Motivanki", just for reference.

**Comment by Hovvdy** [comment] 2022-07-27 16:16
I will be able to test this later this evening whenever I am not studying. I just disabled the AnKing's add on "Custom Background Image and Gear Icon" because I thought two conflicting re-design addons could be causing the issue. Disabling this and restarting still resulted in the glitch being able to be replicated.

**Comment by Shirajuki** [comment] 2022-10-10 18:22
Hellohello!
I see that this is a problem occuring to more than one and thus believe that it's an add-on conflict issue here.
I have been putting this on hold for a while now, but I'll try to find a fix for this and hopefully it gets fixed soon!

**Comment by Shirajuki** [comment] 2022-10-10 19:20
Hmmm, I tried installing all of the mentioned add-ons but can't seem to reproduce the problem :c
Does the problem still occur?

**Comment by Shirajuki** [comment] 2022-10-12 16:26
Hello again!
Hmm... the occurrence is very strange. Could you try to disable all addons and testing it again?
If disabling all the addons and the problem still occurs, then it has to be some code that is giving the problem.
If the problem is fixed, however, then the reason is on the addon compatibility. We can figure out which addon it is by re-enabling the addons you use one by one and testing for the occurrence each time you re-enable an addon.
Could you please try that and update me the results? :)

**Comment by Hovvdy** [comment] 2022-10-12 16:28
I disabled all of them just now, and it works fine. I will enable one by one to see the causative agent.

**Comment by Hovvdy** [comment] 2022-10-12 16:34
I found the issue. It was this addon https://ankiweb.net/shared/info/1898790263

**Comment by Shirajuki** [comment] 2022-10-12 17:25
Ahh, it is good that the culprit was found tho!
It was actually one of the addons I didn't test since you had said earlier that the problem occurred before you added "Contanki" haha. I'll try to see if I can figure out a fix for that when I have the time. I'll hopefully give you an update soon! ;)

**Comment by Hovvdy** [comment] 2022-10-12 17:59
Yeah, I was confused by that as well, but upon testing it was the only one that affected it haha.

**Closed** 2022-10-27 22:51 UTC
Labels: bug, addon compatibility

**Comment by Shirajuki** [comment] 2022-10-27 22:52
A fix for this add-on was recently added! It will be pushed out along the new update of Anki-redesign. Thank you for waiting! :D
