### ISSUE TITLE
No top menu bar add-on config bar

### ISSUE THREAD

**Issue by kaliisaaa** [Shirajuki/anki-redesign#25] opened 2022-07-03 22:00 UTC
I downloaded the addon, and I can edit a few things from the general addon menu aby using the "configure" button, however, there is no menu bar button for the addon. I disabled all my other addons because I thought it might be interfering with this addon, but the button was still not there after restarting Anki. I'm running 2.1.46 btw, thanks.

**Comment by Shirajuki** [comment] 2022-07-04 21:07
Hello! Oh no, this is good to hear. 😟
If you are using Mac, refer to the issue #26. The addon is a little bit strange on Mac systems and completely replaces Anki's preferences button on the toolbar. Hopefully I'll find a fix for this soon and gets and update released.
If otherwise, could you add an image showing the issue? I'll try to follow up on this thread closely with you so that this issue gets fixed :)

All in all, thank you very much for being a user of Anki-redesign!

**Comment by Shirajuki** [comment] 2022-07-27 06:55
Hello again!
I am here to inform that a new version was just recently pushed out, including a possible fix to this issue. Does the same problem still happen with the newly updated release of Anki-redesign?

**Comment by kaliisaaa** [comment] 2022-07-27 16:38
Hi! Sorry, I forgot to respond to the first message. I am having the same issue as #26 where the Anki-Redesign tab shows up in my Preferences. The update didn't fix it, unfortunately 😕

**Comment by Shirajuki** [comment] 2022-07-27 17:31
Hello! It is all well, thank you for the response. This is actually not good...
I'll have to revisit this issue on a future update. Hopefully you won't wait so long!
Once again, thank you very much for being a user of Anki-redesign, as well as contributing to the add-on!

**Comment by Shirajuki** [comment] 2022-08-22 18:34
Hello again!
I am once again back again here to inform that a new version was just recently pushed out, including a possible fix to this issue? The fix is done naively by simply moving the Anki-redesign tab to the Tools menubar. Hopefully, you can open both Anki's default preferences as well as Anki-redesign's now! I'll leave this issue open for now, I'll appreciate if you can tell me if the issue is fixed yet or not! 

Once again, thank you very much for contributing to the development of Anki-redesign! :D

**Comment by Shirajuki** [comment] 2022-08-23 10:48
Fixed in the latest update (v0.1.5). Closing this issue, see #26 :)

**Closed by Shirajuki** 2022-08-23 10:48 UTC
Labels: bug
