### ISSUE TITLE
[Bug] Add-on replaces Anki's preferences pane

### ISSUE THREAD

**Issue by kvn1351** [Shirajuki/anki-redesign#26] opened 2022-07-04 02:02 UTC
Unfortunately, this addon replaces Anki's preference pane (at least on my system). I don't understand why it doesn't show up under tools or on a separate column even. But as of now, it replaces the settings pane and thus I have to disable the addon to get back into Anki's settings pane.

![image](https://user-images.githubusercontent.com/11823348/177068521-75b698ab-3467-4fcc-9814-1ee582a2388d.png)
^ When I press this, it goes into the addon's settings.

![image](https://user-images.githubusercontent.com/11823348/177068995-b9638061-3050-4af7-b9c2-3bd391296b64.png)
^ As you can see, the addon's settings isn't to be found anywhere else.

Version 2.1.54 (b6a7760c)
Python 3.9.7 Qt 6.3.1 PyQt 6.3.1
12.4 macOS M1

Edit: Thanks a lot in advance and for all of your work so far :)

**Comment by Shirajuki** [comment] 2022-07-04 20:59
Hello!
This is actually a known problem with how Anki-redesign is configured and happens on all Mac systems since 2.1.50?, sadly. I still don't know if it's due to the release of QT6 and I am using a deprecated way of adding things to the toolbar or not yet, but I am looking for a fix for this with the best of my abilities! I'll be quite busy the next 2 weeks due to vacation but hopefully I'll be able to get a fix for this pushed out soon! I hope this won't a big hindrance for you in the mean time using the addon, thank you very much for being a user of Anki-redesign!

**Comment by kvn1351** [comment] 2022-07-04 22:45
No problem really! It's a bit cumbersome, but I fully understand and will patiently await the update.

Thanks a lot for this awesome addon :)
And have a fantastic vacation!

**Comment by Shirajuki** [comment] 2022-07-27 06:55
Hello again!
I am here to inform that a new version was just recently pushed out, including a possible fix to this issue. Does the same problem still happen with the newly updated release of Anki-redesign?

**Comment by kvn1351** [comment] 2022-07-27 08:57
Hi, I still have the very same issue unfortunately with the latest version.

**Comment by Shirajuki** [comment] 2022-07-27 17:30
Hmm, that is actually not good to hear... I still can't figure out the reason the Anki's preference pane gets replaced. It just doesn't really make sense as it is implemented just the same as what was instructed at: https://addon-docs.ankiweb.net/a-basic-addon.html. I have gotten your email as well, thanks! I have been trying fix this problem without using a macOS vm thus far, but I guess I'll have to set one up as it seems fixing this in a blackbox matter is quite difficult. I won't have a strong enough PC until then, this issue will therefore be set on hold until then.

The next plan would be to add in some other add-on compatibility fixes, and working on the theming part of the add-on, fixing the different color themes as well as making it easier for a user to create their own custom themes. I'll be then taking a look at this again after that.
Thank you very much for the bug report, contributing to the development of Anki-redesign! I hope you'll wait till then! :D

**Comment by Shirajuki** [comment] 2022-08-22 18:34
Hello again!
I am once again back again here to inform that a new version was just recently pushed out, including a possible fix to this issue? The fix is done naively by simply moving the Anki-redesign tab to the Tools menubar. Hopefully, you can open both Anki's default preferences as well as Anki-redesign's now! I'll leave this issue open for now, I'll appreciate if you can tell me if the issue is fixed yet or not! 

Once again, thank you very much for contributing to the development of Anki-redesign! :D

**Comment by kvn1351** [comment] 2022-08-23 00:24
```
An add-on you installed failed to load. If
problems persist, please go to the Tools>Add
ons menu, and disable or delete the add-on.
When loading 'Redesign':
Traceback (most recent call last):
File "aqt.addons", line 244, in load Addons
File"/Users/kevinjohansson/Library/Application
Support/Anki2/addons21/1914733489/
_init__.py", line 1, in ‹module>
from .redesign import Redesign
File"/Users/kevinjohansson/Library/Application
Support/Anki2/addons21/1914733489/
redesign.py", line 44, in «module>
from .actions_and_settings import
File"/Users/kevinjohansson/Library/Application
Support/Anki2/addons21/1914733489/
ions_and_settings.py", line 8, in <module>
from .color_map import ColorMap Window
File"/Users/kevinjohansson/Library/Application
Support/Anki2/addons21/1914733489/
color_map.py", line 6, in <module>
from •gui import create, button,
remove_layout,AddonDialog
File"/Users/kevinjohansson/Library/Application
Support/Anki2/addons21/1914733489/gui.py",
line 3, in «module>
from .languages import.
File"/Users/kevinjohansson/Library/Application
Support/Anki2/addons21/1914733489/
languages.py", line 4, in ‹module>
from anki.lang import getLang,. as
fallback_translation
ImportError: cannot import name 'getLang' from
'anki.lang' (unknown location)
```

**Comment by Shirajuki** [comment] 2022-08-23 07:56
Hello! Oh no! That's the wrong Add-on you've installed! https://ankiweb.net/shared/info/1914733489 😋 

Use this one instead: https://ankiweb.net/shared/info/308574457

**Comment by kvn1351** [comment] 2022-08-23 10:43
Hahahaha what a silly mistake. Sorry for that. It works great now! Thanks a lot!

**Closed** 2022-08-23 10:43 UTC
Labels: bug
