### ISSUE TITLE
small bottoms in the "add cards " window

### ISSUE THREAD

**Issue by ahmad123ahmad** [Shirajuki/anki-redesign#52] opened 2022-10-24 12:34 UTC
hello there, i like this add on but as the picture attached to this issue speaks for itself, the bottoms of add cards window became much smaller which is kind of annoying even though I use shortcuts for the most part but still
in the pic I attached the window with the add on (the lower one) it looks squeezed because I resized it to fit the pic canva but i meant in terms of buttom size and width you can see this issue clearly
, I posted another issue with this add on on this github page too, hoping they get fixed soon
![Untitled](https://user-images.githubusercontent.com/116543025/197525918-f03bb6fb-fba3-4218-829d-fa8fae0081b2.png)

**Comment by Shirajuki** [comment] 2022-12-09 01:10
Hello! This indeed does not seem right.
I have unfortunately been quite busy these past few months due to studies and will not be working on this add-on until after christmas. I will however, prioritize this and see if I can find a fix for this in the nearest future.
Hopefully this will get fixed in the next update. Thank you for all the issues as well!

**Comment by Shirajuki** [comment] 2023-02-01 00:03
Hello again, I believe that I've found the culprit to these changes. A fix for this will hopefully be added in the next update (v0.1.9). Hopefully you won't be waiting that long.

**Closed** 2023-02-04 18:38 UTC
Labels: bug

**Comment by Shirajuki** [comment] 2023-02-04 18:54
Hello! I have just recently pushed out a new update fixing this issue. The problem is closely related to the font-size set in Anki-redesign preferences. Anki sets it as 15px by default, so if you want it to be similar in size, then set the font to 15px as well. :)

Feel free to open a new issue if the problem is still not fixed. Thank you for being a user of Anki-redesign!
