### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by Jerfain** [Shirajuki/anki-redesign#24] opened 2022-06-26 09:28 UTC
The latest version of Anki has been able to switch between day mode and night mode as the system switches. Although Anki-Redesign supports night mode, it cannot automatically switch the background to dark when Anki switches to night mode, below is my Anki main interface, which is the situation of Anki after the system automatically switches from light color to dark color, we can see from the picture We can see from the picture that Anki's top bar is already dark and the plugin Heatmap has also switched to dark, but Anki-Redesign has not. Now I still need to manually turn off Anki and turn it on again to achieve the dark and light color change.
<img width="1920" alt="图片" src="https://user-images.githubusercontent.com/69144012/175807996-03958b4d-ffbf-427f-b169-b305de718896.png">

**Comment by Jerfain** [comment] 2022-06-26 09:36
3.I'm using a Mac system, and in the latest version of Anki (2.1.54), if my Anki language is English, then when I click on Anki preferences, the Redesign preferences pop up and the Anki-Redesign settings bar does not appear in the top bar, but when I switch the Anki language to Chinese, the Anki-Redesign I suspect that the variables set by Redsign have replaced the variables set by Anki itself in the code, but when Anki becomes Chinese, the variable names set will not cause a conflict.
<img width="1920" alt="图片" src="https://user-images.githubusercontent.com/69144012/175808276-aff3ab39-8b5d-4412-95ef-a6c9b94e00c9.png">
![Uploading 图片.png…]()

**Comment by Shirajuki** [comment] 2022-06-27 06:12
Hello Jerfain! 👋
Thank you very much for a detailed issue reporting the bugs you've found. Lots of new issues I didn't understand of beforehand, the embedded images helped a lot! I'll work on an update this week and hopefully it will fix all these problems as well as others then! Thank you for helping with the development as well as being a user of Anki-redesign! 🥳

**Comment by Shirajuki** [comment] 2022-07-02 22:57
Hello again!
A new update of Anki-Redesign is now available! Anki-redesign now supports automatically switching the dark/light theme. Hopefully you don't need to manually turn Anki on and off again to achieve the dark and light color change. I sadly can't reproduce the problem where the Anki-Redesign settings bar replaces Anki's default preference button as I myself use Windows. However, I have tried to change the way the settings bar is being added and saved, and hopefully this bug is fixed in this update as well!

I'll leave this issue open in case this is not the case :)

**Comment by Jerfain** [comment] 2022-07-03 05:40
Hi, I've received and made the update, the first issue I mentioned above, which is the day night mode switch has been fixed, I also noticed that a new theme has been added with this update, I'm curious if Catppuccin is your own custom theme, I've never seen this theme on other code editors and it's really comfortable with the night mode background color. Also it's a shame the second issue wasn't addressed, but I use it all in Chinese mode, so this issue isn't that high of a priority for me. Also I noticed that this new version solves the problem with the display of the start learning page after clicking on a deck. Thanks a lot for your work, I really like anki-redesign!
<img width="876" alt="图片" src="https://user-images.githubusercontent.com/69144012/177026532-9fceec96-ea72-436e-9908-2cc00694b64d.png">

**Comment by Jerfain** [comment] 2022-07-03 06:03
Another question I have is what is the difference between checked and unchecked in the plugin compatibility option? For example, I have the Advanced Review Bar Bottom plugin, but I don't feel the difference after checking and unchecking it.
<img width="420" alt="图片" src="https://user-images.githubusercontent.com/69144012/177027067-63cb554a-7ee2-4578-a8f1-97216275865b.png">
<img width="420" alt="图片" src="https://user-images.githubusercontent.com/69144012/177027069-629a1abd-a474-4e73-8099-4b05e9e224a2.png">

**Comment by Shirajuki** [comment] 2022-07-03 10:34
Hi! I am glad the some issues was somewhat fixed! It is always difficult to push out fixes for multiple platforms when you don't have the different devices available. The second issue seems to only be seen on Mac users and that makes it a little bit tricky for me to find a solution for, I'll however try to take more time looking into it in the future. :D And yes! Catppuccin is a custom theme taken with inspiration from https://github.com/catppuccin/catppuccin. I myself really like the color palette and find it very comfortable to look at. I use it as my daily driver. 

Aha I guess I rushed out this update and haven't gotten to add a tooltip explaining the usage of the different fixes yet, I'll remember to add this in the next update. The Advanced Review Bottom Bar compatibility fix-check addresses issue #22 , which is a fix for the styling on the button on the overview page as well as making it possible to style the buttons through ARBb configuration panel, instead of using styling it manually through Anki-redesign's CSS injection.

Once again, thank you for helping with the development of Anki-redesign! Your images with the labels and arrows are very helpful as it makes it very easy to follow!

**Comment by Jerfain** [comment] 2022-07-03 10:43
Thanks! I've changed my vscode theme to Catppuccin and it looks very comfortable and unified with Anki, thanks again, no need to reply to this entry：D

**Comment by Shirajuki** [comment] 2022-07-03 10:56
Aha that is great! I'll be closing this issue then!
Feel free to open another issue if there ever comes an issue when using Anki-redesign in the future as well! 
Opening issues does really help with the development of the addon a lot, so thank you again!

**Closed by Shirajuki** 2022-07-03 10:56 UTC
Labels: bug
